theme: jekyll-theme-hacker
title: AVA360VR (Annotate, Visualise, Analyse 360 Video in VR)
description: Help pages and tutorials
URL: "https://bigsoftvideo.github.io/AVA360VR"
image: "/images/logo.png"
markdown: GFM
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - contributing.md
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"

