theme: jekyll-theme-hacker
name: AVA360VR Beta-testing
description: Help pages for beta-testers
URL: "https://bigsoftvideo.github.io/AVA360VR-beta-testing"
image: "/images/logo.png"
markdown: GFM
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - contributing.md
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"

