name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Congratulations on submitting your first issue to the AVA developers...'
        pr-message: 'Congratulations on submitting your first pull request to the AVA developers...'
